# Generated by Django 5.1.5 on 2025-01-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('capacidad_golpes', models.PositiveIntegerField(blank=True, null=True)),
                ('cont_golpes_actual', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
                ('disponibilidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_planificada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('duracion_horas', models.FloatField(blank=True, null=True)),
                ('golpes_a_realizar', models.PositiveIntegerField(blank=True, null=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='gestion_mantenimiento.matriz')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='gestion_mantenimiento.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mttr_horas', models.FloatField(blank=True, null=True)),
                ('mtbf_golpes', models.PositiveIntegerField(blank=True, null=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion_mantenimiento.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='HerramientasPorOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='gestion_mantenimiento.herramienta')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_usadas', to='gestion_mantenimiento.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MatricesPorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.matriz')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoPorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestosPorOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='gestion_mantenimiento.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='gestion_mantenimiento.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='TecnicosPorOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='gestion_mantenimiento.ordentrabajo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_asignadas', to='gestion_mantenimiento.tecnico')),
            ],
            options={
                'unique_together': {('orden_trabajo', 'tecnico')},
            },
        ),
    ]
