# Generated by Django 5.1.5 on 2025-01-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='fabricante',
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MatricesPorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.matriz')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoPorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_mantenimiento.proyecto')),
            ],
        ),
    ]
